// Deterministic, reviewed locale strings — NEVER generated by Workers AI
// at render time. Two kinds of fixed content live here:
//
//   1. Localized labels for the application's internal status codes
//      (STATUS_OPTIONS below never changes independently of this file —
//      see worker/src/routes/staff.js, which imports STATUS_OPTIONS from
//      here so the two can never drift apart).
//   2. The payment-discrepancy safety warning shown beneath a bilingual
//      payment description (Phase 3.1 Section 18).
//
// Both are looked up by the client's own preferred_communication_language,
// never translated per-request — this is fixed UI/safety copy, not
// dynamic staff-authored prose (see Phase 3.1 Section 21).

export const STATUS_OPTIONS = [
  "enquiry_received", "under_review", "documents_required", "documents_received",
  "preparing_application", "submitted", "awaiting_authority_action",
  "additional_information_required", "completed",
];

const STATUS_LABELS = {
  en: {
    enquiry_received: "Enquiry received",
    under_review: "Under review",
    documents_required: "Documents required",
    documents_received: "Documents received",
    preparing_application: "Preparing application",
    submitted: "Submitted",
    awaiting_authority_action: "Awaiting authority action",
    additional_information_required: "Additional information required",
    completed: "Completed",
  },
  "zh-CN": {
    enquiry_received: "已收到咨询",
    under_review: "审核中",
    documents_required: "需要提交材料",
    documents_received: "材料已收到",
    preparing_application: "申请准备中",
    submitted: "已提交",
    awaiting_authority_action: "等待相关机构处理",
    additional_information_required: "需要补充信息",
    completed: "已完成",
  },
  "zh-Hant": {
    enquiry_received: "已收到諮詢",
    under_review: "審核中",
    documents_required: "需要提交文件",
    documents_received: "文件已收到",
    preparing_application: "申請準備中",
    submitted: "已提交",
    awaiting_authority_action: "等待相關機關處理",
    additional_information_required: "需要補充資訊",
    completed: "已完成",
  },
  ko: {
    enquiry_received: "문의 접수됨",
    under_review: "검토 중",
    documents_required: "서류 제출 필요",
    documents_received: "서류 접수됨",
    preparing_application: "신청서 준비 중",
    submitted: "제출됨",
    awaiting_authority_action: "관계 기관 처리 대기 중",
    additional_information_required: "추가 정보 필요",
    completed: "완료됨",
  },
  ja: {
    enquiry_received: "お問い合わせを受け付けました",
    under_review: "確認中",
    documents_required: "書類が必要です",
    documents_received: "書類を受領しました",
    preparing_application: "申請書類準備中",
    submitted: "提出済み",
    awaiting_authority_action: "関係機関の処理待ち",
    additional_information_required: "追加情報が必要です",
    completed: "完了",
  },
  vi: {
    enquiry_received: "Đã nhận yêu cầu",
    under_review: "Đang xem xét",
    documents_required: "Cần bổ sung hồ sơ",
    documents_received: "Đã nhận hồ sơ",
    preparing_application: "Đang chuẩn bị hồ sơ",
    submitted: "Đã nộp hồ sơ",
    awaiting_authority_action: "Đang chờ cơ quan chức năng xử lý",
    additional_information_required: "Cần bổ sung thông tin",
    completed: "Hoàn tất",
  },
};

// Falls back to the English label (never guesses, never invents a label
// dynamically) for a null/'other'/unrecognized preferred language, and to
// the raw status code only if the code itself is somehow unrecognized —
// which should never happen since STATUS_OPTIONS is the single source of
// truth every caller validates against.
export function getLocalizedStatusLabel(status, language) {
  const table = STATUS_LABELS[language] || STATUS_LABELS.en;
  return table[status] || STATUS_LABELS.en[status] || String(status).replace(/_/g, " ");
}

const PAYMENT_DISCREPANCY_WARNING = {
  en: "If the translated description appears inconsistent with the English original, please contact Foreign Immigration Services before making payment.",
  "zh-CN": "如果翻译说明与英文原文内容不一致，请在付款前联系 Foreign Immigration Services。",
  "zh-Hant": "如果翻譯說明與英文原文內容不一致，請在付款前聯絡 Foreign Immigration Services。",
  ko: "번역된 설명이 영어 원문과 일치하지 않는 것으로 보이는 경우, 결제 전에 Foreign Immigration Services로 문의해 주십시오.",
  ja: "翻訳された説明文が英語の原文と異なっているように見える場合は、お支払いの前に Foreign Immigration Services までご連絡ください。",
  vi: "Nếu phần mô tả đã dịch có vẻ không khớp với bản gốc tiếng Anh, vui lòng liên hệ Foreign Immigration Services trước khi thanh toán.",
};

export function getPaymentDiscrepancyWarning(language) {
  return PAYMENT_DISCREPANCY_WARNING[language] || PAYMENT_DISCREPANCY_WARNING.en;
}

// Heading for the translated half of a bilingual payment description
// (Phase 3.1 Section 17's own example shows a native-language heading —
// "中文说明" rather than a generic "Translated Description" — so this is
// a small deterministic lookup, never generated per-request.
const TRANSLATED_DESCRIPTION_HEADING = {
  "zh-CN": "中文说明",
  "zh-Hant": "中文說明",
  ko: "한국어 설명",
  ja: "日本語の説明",
  vi: "Mô tả bằng tiếng Việt",
};

export function getTranslatedDescriptionHeading(language) {
  return TRANSLATED_DESCRIPTION_HEADING[language] || "Translated Description";
}
